### ISSUE TITLE
Crash at second compilation

### ISSUE THREAD

**Issue by jvtrudel** [python-cmake-buildsystem/python-cmake-buildsystem#180] opened 2017-02-15 02:04 UTC
IDE:QtCreator + Compiler:  MSVC 

Everything works when I compile for the first time. Then, I change CMakeLists.txt or I add an option and it crash with error:

      Fatal error C1038: Cannot open include file: 'importlib_external.h': No such file or directory

Even if I clean the project and clear cmake configuration, it still don't regenerate correctly importlib_external.h. 

The only hack I found is to remove all files in my build directory and to throw away the python source directory.

**Comment by jcfr** [comment] 2017-11-06 04:08
Not able to reproduce the issue with the current version of the build system (using CMake 3.9, VS 2015 and QtCreator), I am closing.

Do not hesitate to open a new issue if you still experience problem.

**Closed by jcfr** 2017-11-06 04:08 UTC
Labels: bug
