### ISSUE TITLE
sysv.S:383:2: error: missing .ascii/.string

### ISSUE THREAD

**Issue by johnmudd** [python-cmake-buildsystem/python-cmake-buildsystem#56] opened 2015-07-12 15:22 UTC
I was hoping to use this to build a static python. But first I'm just trying to follow the README example.

```
$ mkdir scratch
$ cd ~/scratch
$ git clone git://github.com/davidsansome/python-cmake-buildsystem
$ mkdir -p python-build && mkdir -p python-install
$ cd python-build
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=${HOME}/scratch/python-install ../python-cmake-buildsystem
$ make -j2
...
[  8%] Building C object CMakeBuild/extensions/CMakeFiles/extension_csv.dir/home/mudd/scratch/Python-2.7.8/Modules/_csv.c.o
/home/mudd/scratch/python-build/../Python-2.7.8/Modules/_ctypes/libffi/src/x86/sysv.S:383:2: error: missing .ascii/.string
#error missing .ascii/.string
 ^
1 error generated.
make[2]: *** [CMakeBuild/Modules/_ctypes/libffi/src/x86/sysv.o] Error 1
make[1]: *** [CMakeBuild/extensions/CMakeFiles/extension_ctypes.dir/all] Error 2
```

I'm running Ubuntu 14.04 with cmake 2.8.12.2 and gcc 4.8.4.

Any suggestions?

**Comment by jcfr** [comment] 2015-07-12 15:27
Thanks for reporting the issue. Waiting this is addressed, if you don't need `ctypes` extension, you could workaround the issue by passing `-DENABLE_CTYPES:BOOL=0`

**Comment by johnmudd** [comment] 2015-07-12 15:43
Thanks. It does build without errors when I add -DENABLE_CTYPES:BOOL=0. I can use that temporarily.

**Comment by jcfr** [comment] 2015-08-05 23:22
I am not able to reproduce this problem using a similar configuration. Which version of Python where using the build system with ? Could you try against using the current master ?
Thanks

**Comment by jcfr** [comment] 2015-08-25 08:23
Since i am not able to reproduce the problem, the problem is most likely fixed in `master` I am closing the issue. Please re-open if you still have a problem.

**Closed by jcfr** 2015-08-25 08:23 UTC
