### ISSUE TITLE
SET HAVE_ALLOCA_H not obeyed?

### ISSUE THREAD

**Issue by tony** [python-cmake-buildsystem/python-cmake-buildsystem#134] opened 2016-06-12 00:06 UTC
Closing in on FreeBSD support

ef790ee133b48439fd3e372af89eca17ac7dbee5

FreeBSD 11-CURRENT AMD64

Python 3.5.1, CMake 3.5.1

```
if(${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD")
  set(SETPGRP_HAVE_ARG 1)
  set(HAVE_SYS_SYS_DOMAIN_H 0)
  set(HAVE_ALLOCA_H 0)
  set(HAVE_ALLOCA 0)
endif()
```

```diff
diff --git a/cmake/ConfigureChecks.cmake b/cmake/ConfigureChecks.cmake
index 395ad36..a389906 100644
--- a/cmake/ConfigureChecks.cmake
+++ b/cmake/ConfigureChecks.cmake
@@ -109,6 +109,13 @@ if(USE_SYSTEM_SQLITE3)
     find_library(SQLITE3_LIBRARY sqlite3)
 endif()
 
+if(${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD")
+  set(SETPGRP_HAVE_ARG 1)
+  set(HAVE_SYS_SYS_DOMAIN_H 0)
+  set(HAVE_ALLOCA_H 0)
+  set(HAVE_ALLOCA 0)
+endif()
+
 if(WIN32)
   set(M_LIBRARIES )
   set(HAVE_LIBM 1)
```

```
[229/423] Building C object CMakeBuild/extensions/extension_ctypes/CMakeFiles/extension_ctypes.dir/home/x/study/c++/kakoune/build/Python-3.5.1/Modules/_ctypes/libffi/src/closures.c.o
FAILED: CMakeBuild/extensions/extension_ctypes/CMakeFiles/extension_ctypes.dir/home/x/study/c++/kakoune/build/Python-3.5.1/Modules/_ctypes/libffi/src/closures.c.o 
/usr/bin/cc  -Dextension_ctypes_EXPORTS -I/home/x/study/c++/kakoune/build/Python-3.5.1/Include -Ibin -I/home/x/study/c++/kakoune/build/Python-3.5.1/Python -I/home/x/study/c++/kakoune/build/Python-3.5.1/Modules/_ctypes/libffi/src/x86 -I/home/x/study/c++/kakoune/build/Python-3.5.1/Modules/_ctypes/libffi/include -I/home/x/study/c++/kakoune/build/Python/cmake -Wall -g -O3 -DNDEBUG -fPIC -MMD -MT CMakeBuild/extensions/extension_ctypes/CMakeFiles/extension_ctypes.dir/home/x/study/c++/kakoune/build/Python-3.5.1/Modules/_ctypes/libffi/src/closures.c.o -MF CMakeBuild/extensions/extension_ctypes/CMakeFiles/extension_ctypes.dir/home/x/study/c++/kakoune/build/Python-3.5.1/Modules/_ctypes/libffi/src/closures.c.o.d -o CMakeBuild/extensions/extension_ctypes/CMakeFiles/extension_ctypes.dir/home/x/study/c++/kakoune/build/Python-3.5.1/Modules/_ctypes/libffi/src/closures.c.o   -c /home/x/study/c++/kakoune/build/Python-3.5.1/Modules/_ctypes/libffi/src/closures.c
In file included from /home/x/study/c++/kakoune/build/Python-3.5.1/Modules/_ctypes/libffi/src/closures.c:34:
/home/x/study/c++/kakoune/build/Python-3.5.1/Modules/_ctypes/libffi/include/ffi_common.h:23:12: fatal error: 'alloca.h' file not found
#  include <alloca.h>
           ^
1 error generated.
[230/423] Building C object CMakeBuild/extensions/extension_ctypes/CMakeFiles/extension_ctypes.dir/home/x/study/c++/kakoune/build/Python-3.5.1/Modules/_ctypes/stgdict.c.o
[231/423] Building C object CMakeBuild/extensions/extension_ctypes/CMakeFiles/extension_ctypes.dir/home/x/study/c++/kakoune/build/Python-3.5.1/Modules/_ctypes/cfield.c.o
[232/423] Building C object CMakeBuild/extensions/extension_unicodedata/CMakeFiles/extension_unicodedata.dir/home/x/study/c++/kakoune/build/Python-3.5.1/Modules/unicodedata.c.o
[233/423] Building C object CMakeBuild/extensions/extension_ctypes/CMakeFiles/extension_ctypes.dir/home/x/study/c++/kakoune/build/Python-3.5.1/Modules/_ctypes/_ctypes.c.o
[234/423] Building C object CMakeBuild/extensions/extension_decimal/CMakeFiles/extension_decimal.dir/home/x/study/c++/kakoune/build/Python-3.5.1/Modules/_decimal/_decimal.c.o
ninja: build stopped: subcommand failed.
ninja: build stopped: subcommand failed.
```

``cmake --system-information`` output: [cmake-sysinfo.txt](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/files/310577/cmake-sysinfo.txt)

Q: https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/master/cmake/fficonfig.h is that unusued, ammended somehow during build, or auto-generated via https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/master/cmake/config-unix/pyconfig.h.in?

**Comment by tony** [comment] 2016-06-12 00:17
pyconfig.h.in has a nice ``cmakedefine`` system.

``fficonfig.h`` on the other hand doesn't have a setup like that, its taken in raw at https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/4856e34c97141b930a27f563d14bd44edd63ac8f/cmake/extensions/CMakeLists.txt#L314.

I see a dir of patches accumulating, but I think the most flexible approach would be ``fficonfig.h`` getting the ``configure_file()`` treatment like [``pyconfig.h.in`` does](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/ef790ee133b48439fd3e372af89eca17ac7dbee5/CMakeLists.txt#L348).

**Comment by jcfr** [comment] 2016-06-12 05:54
> pyconfig.h.in has a nice ``cmakedefine`` system.

Thanks.

> I think the most flexible approach would be ``fficonfig.h`` getting the ``configure_file()`` treatment like [``pyconfig.h.in`` does](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/ef790ee133b48439fd3e372af89eca17ac7dbee5/CMakeLists.txt#L348).

Agreed. That would be a nice project to take one.

In the mean time, do you think you could setup a dashboard to test the build system on freebsd ?

**Comment by tony** [comment] 2016-06-12 05:58
@jcfr Yes got you covered, going to QA it a bit more. 

working on a another issue at the moment, but while I do that, I'm using this successfully https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/compare/master...tony:freebsd-support.  Anything pop out at you?

**Comment by jcfr** [comment] 2016-06-12 06:24
@tony Thanks for working on the freebsd support, that is awesome :smile: 

I posted few comments.

(( Headed to :zzz: , on EST timezone ))

**Comment by jcfr** [comment] 2016-06-17 06:14
Closing. This is a duplicate of #136 and #135

**Closed by jcfr** 2016-06-17 06:14 UTC
